//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public int idBank { get; set; }
        public string tenNganHang { get; set; }
        public string kyHieu { get; set; }
        public string image { get; set; }
        public string tenTK { get; set; }
        public string soTK { get; set; }
        public string loaiTien { get; set; }
        public string chiNhanh { get; set; }
    }
}
